---
- name: Add ICINGA Repo
  yum_repository:
    name: icinga-stable-release
    description: "ICINGA (stable release for epel)"
    baseurl: https://packages.icinga.com/epel/$releasever/release/
    gpgkey: https://packages.icinga.org/icinga.key
    gpgcheck: yes

- name: install icinga2 packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - icinga2-bin
    - icinga2-selinux
    - nagios-plugins-all

- name: create /etc/icinga2/pki directory
  file: path=/etc/icinga2/pki state=directory owner=icinga group=icinga

# [root@red etc]# mkdir -p /etc/icinga2/features-available
# [root@red etc]# mkdir -p /etc/icinga2/features-enabled
# conf.d
# repository.d
# get /etc/icinga2/icinga2.conf
# fix permissions

- name: Generate a new local self-signed certificate.
  command: >
    icinga2 pki new-cert --cn {{ ansible_fqdn }}
    --key /etc/icinga2/pki/{{ ansible_fqdn }}.key
    --cert /etc/icinga2/pki/{{ ansible_fqdn }}.crt
  args:
    creates: "/etc/icinga2/pki/{{ ansible_fqdn }}.key"

- name: Request the master certificate from the master host and store it as trusted-master.crt.
  command: >
    icinga2 pki save-cert --key /etc/icinga2/pki/{{ ansible_fqdn }}.key
    --cert /etc/icinga2/pki/{{ ansible_fqdn }}.crt
    --trustedcert /etc/icinga2/pki/trusted-master.crt
    --host {{ icinga2_server }}
  args:
    creates: /etc/icinga2/pki/trusted-master.crt

- name: check if node setup needs happen
  command: grep "^const NodeName = \"{{ ansible_fqdn }}\"$" /etc/icinga2/constants.conf
  register: node_setup
  changed_when: false
  failed_when: false

- name: Get the client ticket from the server
  command: icinga2 pki ticket --cn {{ ansible_fqdn }}
  register: client_ticket
  delegate_to: "{{ icinga2_server }}"
  become: yes
  when: node_setup.rc != 0

- name: Continue with the additional node setup steps.
  shell: >
    icinga2 node setup --ticket {{ client_ticket.stdout }}
    --endpoint {{ icinga2_server }}
    --zone {{ ansible_fqdn }}
    --master_host {{ icinga2_server }}
    --trustedcert /etc/icinga2/pki/trusted-master.crt
  when: node_setup.rc != 0
  notify: restart icinga2

- name: Configure zones
  template:
    src: "{{ item }}.j2"
    dest: "/etc/icinga2/{{ item }}"
    backup: yes
    owner: icinga
    group: icinga
    mode: 0644
  notify: restart icinga2
  with_items:
    - zones.conf

- name: Enable API features
  lineinfile:
    dest: /etc/icinga2/features-available/api.conf
    regexp: "^  {{ item }}"
    line: "  {{ item }} = true"
  notify: restart icinga2
  with_items:
    - accept_commands

- name: Start and enable client
  service:
    name: icinga2
    state: started
    enabled: true
